inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'test/**/*.rb'

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'
  Max: 30

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'config/initializers/devise.rb'
