inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 30